### ISSUE TITLE
NN Checkboxes: All checkboxes are checked on load

### ISSUE THREAD

**Issue by CasperJuulGregersen** [MscrmTools/PCF-Controls#111] opened 2022-11-22 11:14 UTC
When loading the page, all checkboxes are checked.

I have a project table and a tag table. A N:N relation between these two table exists. The control works very well when I manually select or deselect a tag, but when the page is refreshed all tags are checked (however, the saved data are correct)

![image](https://user-images.githubusercontent.com/58981538/203299918-5f3f52f8-019e-4244-8200-e3f8ba4b945a.png)
![image](https://user-images.githubusercontent.com/58981538/203300086-23499cb5-e392-4495-a7b6-3a6e349db324.png)

**Comment by CasperJuulGregersen** [comment] 2022-12-05 19:24
Hi MscrmTools,

Thanks for getting back to me regarding this issue.

I’ve added some screenshots from the configuration, my Tag table and the relationship between this and my Initiative table. The NN-control is inserted on a form in the Initiative table, and I have two records in the Tag table. Please let me know if you have any questions.

***@***.***

***@***.***

***@***.***

***@***.***


Kind Regards / Venlig hilsen,

Casper Lindy Gregersen | Senior Consultant
***@***.*** | +45 2630 8988

www.projectum.com<https://t-eu.xink.io/Tracking/Index/TSoAAFSrAAAV72MA0> | Follow us on LinkedIn<https://t-eu.xink.io/Tracking/Index/TioAAFSrAAAV72MA0> | Follow us on YouTube<https://t-eu.xink.io/Tracking/Index/TyoAAFSrAAAV72MA0>

**Comment by alanrroberts** [comment] 2022-12-16 13:06
I am seeing a similar issue.  By default all of the checkboxes are checked.  I have noticed the following
If I add a subgrid so I can see any related records I have noticed the following...

1) Even though the checkboxes default to selected, there are no records in the associated subgrid.
2) Unticking and ticking checkboxes doesn't add records to the related subgrid
3) Manually adding records to the subgrid and then unticking the checkboxes does cause them to be removed.

So Unticking is removing records but ticking isn't adding them and all checkboxes default to ticked regardless of whether there are related records or not.

All I have configured in the control is the name of the related table, the view and the table column.  I have also tried manually specifying the relationship but this didn't make a difference.

Cheers

Alan

**Comment by MscrmTools** [comment] 2022-12-17 10:30
Would it be possible to get the configuration for the PCF?
Also, are you using latest version?

**Comment by alanrroberts** [comment] 2022-12-17 11:54
Hi, yes it is the latest version. Can you be more specific about what configuration you want? As mentioned above, I have only configured the name of the related table, the view to use and the column to use for the label. Everything else is left blank. The control does correctly show the labels for the records in the related table. Happy to provide any additional info or set up a screen share if that would help.

**Comment by MscrmTools** [comment] 2022-12-17 19:43
A screenshot of the configuration just to be sure I see the whole picture.

**Comment by CasperJuulGregersen** [comment] 2022-12-19 08:38
It’s not a specific configuration, I want – not yet at least, I’m just investigating the PFC control, which looks really nice (besides this issue).

I just noticed that when the form loads, all options are always checked by default. In my test/example above, I have two records (Business and Family) in my list of tags, and only Business is related to the record in the project table, but both Business and Family are checked on form load.


Kind Regards / Venlig hilsen,

Casper Lindy Gregersen | Senior Consultant
***@***.*** | +45 2630 8988

www.projectum.com<https://t-eu.xink.io/Tracking/Index/TSoAAFSrAAAV72MA0> | Follow us on LinkedIn<https://t-eu.xink.io/Tracking/Index/TioAAFSrAAAV72MA0> | Follow us on YouTube<https://t-eu.xink.io/Tracking/Index/TyoAAFSrAAAV72MA0>

**Comment by alanrroberts** [comment] 2022-12-19 08:53
![image](https://user-images.githubusercontent.com/8680997/208385482-c1ffc16a-9202-4534-b41b-57b4e46e50f4.png)
![image](https://user-images.githubusercontent.com/8680997/208385890-fc1cde03-3038-4213-a5d0-d4a820c1ba41.png)
![image](https://user-images.githubusercontent.com/8680997/208385960-23017a2a-44ee-46c9-be05-15b32eef17ce.png)

I've tried with an without specifying the relationship manually.

Thanks

Alan

**Comment by CasperJuulGregersen** [comment] 2022-12-19 09:19
Hi Alan,

“The control does correctly show the labels for the records in the related table.”
Just to be clear, it’s not about the control not showing the labels correctly, it’s about all labels being checked when the form loads.


Kind Regards / Venlig hilsen,

Casper Lindy Gregersen

**Comment by alanrroberts** [comment] 2022-12-19 10:01
Yep that is correct.  All labels all show but are checked.

![image](https://user-images.githubusercontent.com/8680997/208399439-4740e457-6196-45f4-a5c0-148f3f9b3e68.png)

Even though they show checked, they are not marked as related records though.  Unchecking and checking them also doesn't add them as related records.

**Comment by MscrmTools** [comment] 2022-12-19 15:02
When you only have one relationship between both tables, there is no need to specify the relationship. I Don't know if this is the case for your implementation. But can you try not to specify anything in this parameter?

**Comment by alanrroberts** [comment] 2022-12-19 15:07
Yep saw this in the documentation and tried it with and without a field specified and the result is the same.

**Comment by MscrmTools** [comment] 2022-12-19 15:20
This is so weird because I really do not reproduce it... :( 

In the code, the only location where it is ticking checkboxes is [after having read the information](https://github.com/MscrmTools/PCF-Controls/blob/master/NNCheckboxes/NNCheckboxes/index.ts#L760) sent by the platform about related records. I don't see at all how it could check all records...

**Comment by alanrroberts** [comment] 2022-12-19 15:25
Do I need to have any specific settings on the underlying subgrid?  At the moment it looks like this...

![image](https://user-images.githubusercontent.com/8680997/208460274-b7c39f85-42ff-4213-bb40-854288a9abba.png)

**Comment by MscrmTools** [comment] 2022-12-19 15:31
I don't think so...
Do you have any dev skills so that I can ask you to peform some debug in browser console?

**Comment by MscrmTools** [comment] 2022-12-19 15:33
Found it! Maybe... You did not tick "Show related records", so that it sends all records

**Comment by alanrroberts** [comment] 2022-12-19 15:34
I haven't played with PCF controls but have basic js skills if that helps.  Happy to open up the console and check things for you.

**Comment by MscrmTools** [comment] 2022-12-19 15:35
Did you see my latest comment : Found it! Maybe... You did not tick "Show related records", so that it sends all records

**Comment by alanrroberts** [comment] 2022-12-19 15:36
I wondered about that but though it was suppose to show all records (in order to show the ones not selected as well as the selected ones)?  If I try and tick the "show selected records" option in the designer I get an error.

![image](https://user-images.githubusercontent.com/8680997/208462870-eb6013c9-f88d-4c19-b653-f9f389a893d4.png)

**Comment by alanrroberts** [comment] 2022-12-19 15:55
OK, removed/deleted the checkbox list control and checked the "show related records" field with just the standard subgrid showing.  That allowed me to save the form.  Then added the checkbox list control back and saved again.  Now it is behaving a little differently.  

When I open a form the records are no longer all selected :)
Only the correct records are selected :)
If I unselect a record, the record is correctly removed from a subgrid I have showing on the page :)

The only problem I have is that if I deselect a record and click save, the record is correctly removed from the additional standard subgrid I have showing, but on saving, the deselected record in the checkbox list get selected again.

Starting with 2 records selected (checkbox list view at the top, standard subgrid underneath)
![image](https://user-images.githubusercontent.com/8680997/208466160-6d1185c4-afd1-4b88-8dc3-81bbe02b08b6.png)

Deselect the "Has the order..." option 
![image](https://user-images.githubusercontent.com/8680997/208466479-a79321e0-9708-40f9-93e6-04022f0beac9.png)

Refresh the subgrid
![image](https://user-images.githubusercontent.com/8680997/208466637-a3b37e92-67e3-4589-aa2a-b58f2a9e985d.png)

So the subgrid is showing the correct data but the checkbox control has reselected the record.

**Comment by alanrroberts** [comment] 2022-12-19 15:57
p.s. hitting refresh updates the checkbox control so everything matches
![image](https://user-images.githubusercontent.com/8680997/208467188-9e83fdca-c7b8-4a15-9519-7bff1c6f80d7.png)

**Closed** 2022-12-19 16:47 UTC

**Comment by alanrroberts** [comment] 2022-12-19 17:39
Thanks for your help!

**Comment by CasperJuulGregersen** [comment] 2023-02-10 14:15
That approach do also work for me: Add the default subgrid with Show related records selected. Save the form and then change the control to the Checkbox List.

Thanks for looking into this - really helpful!
